---
# Kubernetes 网络配置
pod_network: '10.244.0.0/16'
service_network: '172.16.0.0/16'
dns_clusterip: '172.16.0.10'

# 时间同步配置
time_server_address: 'ntp.aliyun.com'

# 容器运行时配置
container_runtime: 'docker'
docker_data_root: '/var/lib/docker'

# Harbor 配置
harbor_hostname: 'harbor.k8s.local'

# CNI 配置
cni_version: '1.6.2'

# 各个节点的DNS解析
hosts:
- { ip_address: '192.168.0.121', name: 'master01.k8s.local', alias: 'etcd01.k8s.local' }
- { ip_address: '192.168.0.122', name: 'master02.k8s.local', alias: 'etcd02.k8s.local' }
- { ip_address: '192.168.0.123', name: 'master03.k8s.local', alias: 'etcd03.k8s.local' }
- { ip_address: '192.168.0.129', name: 'master.k8s.local', alias: '' }
- { ip_address: '192.168.0.61', name: 'harbor.k8s.local', alias: '' }
